"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = "$directory$git_status$git_branch\n $character"

# --------------------
# Directory
# --------------------
[directory]
format = "[ 󰝰](cyan) [$path]($style)"
truncation_length = 3
truncate_to_repo = false
style = "bold cyan"

# --------------------
# Git Logo (only in repo)
# --------------------
[git_status]
format = "[  ](bold purple)"
disable = false
# --------------------
# Git Branch (!=main)
# --------------------
[git_branch]
symbol = ""
ignore_branches = ["main"]
format = "[$branch](bold yellow)"
style = "bold green"
