add_newline = false

format = "$directory$git_branch$git_status$character"

[directory]
style = "cyan"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = ""
format = " [$branch]"
style = "green"

[git_status]
disabled = true

[character]
success_symbol = "❯"
error_symbol = "❯"